# Generated by Django 3.2.18 on 2023-04-21 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('select1_content', models.CharField(max_length=100)),
                ('select1_image', models.ImageField(blank=True, upload_to='balance_game_images/%Y/%m/%d/')),
                ('select2_content', models.CharField(max_length=100)),
                ('select2_image', models.ImageField(blank=True, upload_to='balance_game_images/%Y/%m/%d/')),
                ('select1_users', models.ManyToManyField(blank=True, related_name='select1_posts', to=settings.AUTH_USER_MODEL)),
                ('select2_users', models.ManyToManyField(blank=True, related_name='select2_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
